#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File    :   fibinet_test.py
@Time    :   2022/04/18 23:38:48
@Author  :   weiguang 
'''
import pandas as pd
import torch
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from deepctr_torch.inputs import SparseFeat, DenseFeat, get_feature_names
from deepctr_torch.models.fibinet import FiBiNET
from deepctr_torch.models import *

data = pd.read_csv('./criteo_sample.txt')
sparse_features = ['C' + str(i) for i in range(1, 27)]
dense_features = ['I' + str(i) for i in range(1, 14)]

data[sparse_features] = data[sparse_features].fillna('-1', )
data[dense_features] = data[dense_features].fillna(0, )
target = ['label']

# 1.特征labelencoder与minMaxScaler
for feat in sparse_features:
    lbe = LabelEncoder()
    data[feat] = lbe.fit_transform(data[feat])
mms = MinMaxScaler(feature_range=(0, 1))
data[dense_features] = mms.fit_transform(data[dense_features])

# 2.将特征进行分类注册（sparse或dense）
fixlen_feature_columns = [SparseFeat(feat, data[feat].nunique()) for feat in sparse_features] \
                       + [DenseFeat(feat, 1, ) for feat in dense_features]

# deepFM中sparse-embedding向量与dense向量都作为DNN输入
linear_feature_columns = fixlen_feature_columns
feature_names = get_feature_names(fixlen_feature_columns)

# 3.将数据分类
train, test = train_test_split(data, test_size=0.3, random_state=20)
train_model_input = {name: train[name] for name in feature_names}
test_model_input = {name: test[name] for name in feature_names}

device = 'cpu'
use_cuda = True
if use_cuda and torch.cuda.is_available():
    print('cuda ready...')
    device = 'cuda:0'

# 4 DeepFM训练,其中linear_feature_columns只是为继承基类
model = FiBiNET(linear_feature_columns=linear_feature_columns, dnn_feature_columns=fixlen_feature_columns,
               task='binary', bilinear_type='interaction', l2_reg_embedding=1e-5, device=device)
model.compile("adam", "binary_crossentropy", metrics=["binary_crossentropy", "auc"])

history = model.fit(train_model_input, train[target].values, batch_size=256, epochs=10, verbose=2,validation_split=0.2)
pred_ans = model.predict(test_model_input, 256)
print(pred_ans)

plt.plot(history.epoch, history.history['loss'])
plt.title('FiBiNET loss curve')
plt.plot(history.epoch, history.history['val_auc'])
plt.title('FiBiNET auc curve')
plt.show()

'''
FiBiNET(
  (embedding_dict): ModuleDict(
    (C1): Embedding(27, 4)
    (C2): Embedding(92, 4)
    (C3): Embedding(172, 4)
    (C4): Embedding(157, 4)
    (C5): Embedding(12, 4)
    (C6): Embedding(7, 4)
    (C7): Embedding(183, 4)
    (C8): Embedding(19, 4)
    (C9): Embedding(2, 4)
    (C10): Embedding(142, 4)
    (C11): Embedding(173, 4)
    (C12): Embedding(170, 4)
    (C13): Embedding(166, 4)
    (C14): Embedding(14, 4)
    (C15): Embedding(170, 4)
    (C16): Embedding(168, 4)
    (C17): Embedding(9, 4)
    (C18): Embedding(127, 4)
    (C19): Embedding(44, 4)
    (C20): Embedding(4, 4)
    (C21): Embedding(169, 4)
    (C22): Embedding(6, 4)
    (C23): Embedding(10, 4)
    (C24): Embedding(125, 4)
    (C25): Embedding(20, 4)
    (C26): Embedding(90, 4)
  )
  (linear_model): Linear(
    (embedding_dict): ModuleDict(
      (C1): Embedding(27, 1)
      (C2): Embedding(92, 1)
      (C3): Embedding(172, 1)
      (C4): Embedding(157, 1)
      (C5): Embedding(12, 1)
      (C6): Embedding(7, 1)
      (C7): Embedding(183, 1)
      (C8): Embedding(19, 1)
      (C9): Embedding(2, 1)
      (C10): Embedding(142, 1)
      (C11): Embedding(173, 1)
      (C12): Embedding(170, 1)
      (C13): Embedding(166, 1)
      (C14): Embedding(14, 1)
      (C15): Embedding(170, 1)
      (C16): Embedding(168, 1)
      (C17): Embedding(9, 1)
      (C18): Embedding(127, 1)
      (C19): Embedding(44, 1)
      (C20): Embedding(4, 1)
      (C21): Embedding(169, 1)
      (C22): Embedding(6, 1)
      (C23): Embedding(10, 1)
      (C24): Embedding(125, 1)
      (C25): Embedding(20, 1)
      (C26): Embedding(90, 1)
    )
  )
  (out): PredictionLayer()
  (SE): SENETLayer(
    (excitation): Sequential(
      (0): Linear(in_features=26, out_features=8, bias=False)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=26, bias=False)
      (3): ReLU()
    )
  )
  (Bilinear): BilinearInteraction(
    (bilinear): ModuleList(
      (0): Linear(in_features=4, out_features=4, bias=False)
      (1): Linear(in_features=4, out_features=4, bias=False)
      (2): Linear(in_features=4, out_features=4, bias=False)
      (3): Linear(in_features=4, out_features=4, bias=False)
      (4): Linear(in_features=4, out_features=4, bias=False)
      (5): Linear(in_features=4, out_features=4, bias=False)
      (6): Linear(in_features=4, out_features=4, bias=False)
      (7): Linear(in_features=4, out_features=4, bias=False)
      (8): Linear(in_features=4, out_features=4, bias=False)
      (9): Linear(in_features=4, out_features=4, bias=False)
      (10): Linear(in_features=4, out_features=4, bias=False)
      (11): Linear(in_features=4, out_features=4, bias=False)
      (12): Linear(in_features=4, out_features=4, bias=False)
      (13): Linear(in_features=4, out_features=4, bias=False)
      (14): Linear(in_features=4, out_features=4, bias=False)
      (15): Linear(in_features=4, out_features=4, bias=False)
      (16): Linear(in_features=4, out_features=4, bias=False)
      (17): Linear(in_features=4, out_features=4, bias=False)
      (18): Linear(in_features=4, out_features=4, bias=False)
      (19): Linear(in_features=4, out_features=4, bias=False)
      (20): Linear(in_features=4, out_features=4, bias=False)
      (21): Linear(in_features=4, out_features=4, bias=False)
      (22): Linear(in_features=4, out_features=4, bias=False)
      (23): Linear(in_features=4, out_features=4, bias=False)
      (24): Linear(in_features=4, out_features=4, bias=False)
      (25): Linear(in_features=4, out_features=4, bias=False)
      (26): Linear(in_features=4, out_features=4, bias=False)
      (27): Linear(in_features=4, out_features=4, bias=False)
      (28): Linear(in_features=4, out_features=4, bias=False)
      (29): Linear(in_features=4, out_features=4, bias=False)
      (30): Linear(in_features=4, out_features=4, bias=False)
      (31): Linear(in_features=4, out_features=4, bias=False)
      (32): Linear(in_features=4, out_features=4, bias=False)
      (33): Linear(in_features=4, out_features=4, bias=False)
      (34): Linear(in_features=4, out_features=4, bias=False)
      (35): Linear(in_features=4, out_features=4, bias=False)
      (36): Linear(in_features=4, out_features=4, bias=False)
      (37): Linear(in_features=4, out_features=4, bias=False)
      (38): Linear(in_features=4, out_features=4, bias=False)
      (39): Linear(in_features=4, out_features=4, bias=False)
      (40): Linear(in_features=4, out_features=4, bias=False)
      (41): Linear(in_features=4, out_features=4, bias=False)
      (42): Linear(in_features=4, out_features=4, bias=False)
      (43): Linear(in_features=4, out_features=4, bias=False)
      (44): Linear(in_features=4, out_features=4, bias=False)
      (45): Linear(in_features=4, out_features=4, bias=False)
      (46): Linear(in_features=4, out_features=4, bias=False)
      (47): Linear(in_features=4, out_features=4, bias=False)
      (48): Linear(in_features=4, out_features=4, bias=False)
      (49): Linear(in_features=4, out_features=4, bias=False)
      (50): Linear(in_features=4, out_features=4, bias=False)
      (51): Linear(in_features=4, out_features=4, bias=False)
      (52): Linear(in_features=4, out_features=4, bias=False)
      (53): Linear(in_features=4, out_features=4, bias=False)
      (54): Linear(in_features=4, out_features=4, bias=False)
      (55): Linear(in_features=4, out_features=4, bias=False)
      (56): Linear(in_features=4, out_features=4, bias=False)
      (57): Linear(in_features=4, out_features=4, bias=False)
      (58): Linear(in_features=4, out_features=4, bias=False)
      (59): Linear(in_features=4, out_features=4, bias=False)
      (60): Linear(in_features=4, out_features=4, bias=False)
      (61): Linear(in_features=4, out_features=4, bias=False)
      (62): Linear(in_features=4, out_features=4, bias=False)
      (63): Linear(in_features=4, out_features=4, bias=False)
      (64): Linear(in_features=4, out_features=4, bias=False)
      (65): Linear(in_features=4, out_features=4, bias=False)
      (66): Linear(in_features=4, out_features=4, bias=False)
      (67): Linear(in_features=4, out_features=4, bias=False)
      (68): Linear(in_features=4, out_features=4, bias=False)
      (69): Linear(in_features=4, out_features=4, bias=False)
      (70): Linear(in_features=4, out_features=4, bias=False)
      (71): Linear(in_features=4, out_features=4, bias=False)
      (72): Linear(in_features=4, out_features=4, bias=False)
      (73): Linear(in_features=4, out_features=4, bias=False)
      (74): Linear(in_features=4, out_features=4, bias=False)
      (75): Linear(in_features=4, out_features=4, bias=False)
      (76): Linear(in_features=4, out_features=4, bias=False)
      (77): Linear(in_features=4, out_features=4, bias=False)
      (78): Linear(in_features=4, out_features=4, bias=False)
      (79): Linear(in_features=4, out_features=4, bias=False)
      (80): Linear(in_features=4, out_features=4, bias=False)
      (81): Linear(in_features=4, out_features=4, bias=False)
      (82): Linear(in_features=4, out_features=4, bias=False)
      (83): Linear(in_features=4, out_features=4, bias=False)
      (84): Linear(in_features=4, out_features=4, bias=False)
      (85): Linear(in_features=4, out_features=4, bias=False)
      (86): Linear(in_features=4, out_features=4, bias=False)
      (87): Linear(in_features=4, out_features=4, bias=False)
      (88): Linear(in_features=4, out_features=4, bias=False)
      (89): Linear(in_features=4, out_features=4, bias=False)
      (90): Linear(in_features=4, out_features=4, bias=False)
      (91): Linear(in_features=4, out_features=4, bias=False)
      (92): Linear(in_features=4, out_features=4, bias=False)
      (93): Linear(in_features=4, out_features=4, bias=False)
      (94): Linear(in_features=4, out_features=4, bias=False)
      (95): Linear(in_features=4, out_features=4, bias=False)
      (96): Linear(in_features=4, out_features=4, bias=False)
      (97): Linear(in_features=4, out_features=4, bias=False)
      (98): Linear(in_features=4, out_features=4, bias=False)
      (99): Linear(in_features=4, out_features=4, bias=False)
      (100): Linear(in_features=4, out_features=4, bias=False)
      (101): Linear(in_features=4, out_features=4, bias=False)
      (102): Linear(in_features=4, out_features=4, bias=False)
      (103): Linear(in_features=4, out_features=4, bias=False)
      (104): Linear(in_features=4, out_features=4, bias=False)
      (105): Linear(in_features=4, out_features=4, bias=False)
      (106): Linear(in_features=4, out_features=4, bias=False)
      (107): Linear(in_features=4, out_features=4, bias=False)
      (108): Linear(in_features=4, out_features=4, bias=False)
      (109): Linear(in_features=4, out_features=4, bias=False)
      (110): Linear(in_features=4, out_features=4, bias=False)
      (111): Linear(in_features=4, out_features=4, bias=False)
      (112): Linear(in_features=4, out_features=4, bias=False)
      (113): Linear(in_features=4, out_features=4, bias=False)
      (114): Linear(in_features=4, out_features=4, bias=False)
      (115): Linear(in_features=4, out_features=4, bias=False)
      (116): Linear(in_features=4, out_features=4, bias=False)
      (117): Linear(in_features=4, out_features=4, bias=False)
      (118): Linear(in_features=4, out_features=4, bias=False)
      (119): Linear(in_features=4, out_features=4, bias=False)
      (120): Linear(in_features=4, out_features=4, bias=False)
      (121): Linear(in_features=4, out_features=4, bias=False)
      (122): Linear(in_features=4, out_features=4, bias=False)
      (123): Linear(in_features=4, out_features=4, bias=False)
      (124): Linear(in_features=4, out_features=4, bias=False)
      (125): Linear(in_features=4, out_features=4, bias=False)
      (126): Linear(in_features=4, out_features=4, bias=False)
      (127): Linear(in_features=4, out_features=4, bias=False)
      (128): Linear(in_features=4, out_features=4, bias=False)
      (129): Linear(in_features=4, out_features=4, bias=False)
      (130): Linear(in_features=4, out_features=4, bias=False)
      (131): Linear(in_features=4, out_features=4, bias=False)
      (132): Linear(in_features=4, out_features=4, bias=False)
      (133): Linear(in_features=4, out_features=4, bias=False)
      (134): Linear(in_features=4, out_features=4, bias=False)
      (135): Linear(in_features=4, out_features=4, bias=False)
      (136): Linear(in_features=4, out_features=4, bias=False)
      (137): Linear(in_features=4, out_features=4, bias=False)
      (138): Linear(in_features=4, out_features=4, bias=False)
      (139): Linear(in_features=4, out_features=4, bias=False)
      (140): Linear(in_features=4, out_features=4, bias=False)
      (141): Linear(in_features=4, out_features=4, bias=False)
      (142): Linear(in_features=4, out_features=4, bias=False)
      (143): Linear(in_features=4, out_features=4, bias=False)
      (144): Linear(in_features=4, out_features=4, bias=False)
      (145): Linear(in_features=4, out_features=4, bias=False)
      (146): Linear(in_features=4, out_features=4, bias=False)
      (147): Linear(in_features=4, out_features=4, bias=False)
      (148): Linear(in_features=4, out_features=4, bias=False)
      (149): Linear(in_features=4, out_features=4, bias=False)
      (150): Linear(in_features=4, out_features=4, bias=False)
      (151): Linear(in_features=4, out_features=4, bias=False)
      (152): Linear(in_features=4, out_features=4, bias=False)
      (153): Linear(in_features=4, out_features=4, bias=False)
      (154): Linear(in_features=4, out_features=4, bias=False)
      (155): Linear(in_features=4, out_features=4, bias=False)
      (156): Linear(in_features=4, out_features=4, bias=False)
      (157): Linear(in_features=4, out_features=4, bias=False)
      (158): Linear(in_features=4, out_features=4, bias=False)
      (159): Linear(in_features=4, out_features=4, bias=False)
      (160): Linear(in_features=4, out_features=4, bias=False)
      (161): Linear(in_features=4, out_features=4, bias=False)
      (162): Linear(in_features=4, out_features=4, bias=False)
      (163): Linear(in_features=4, out_features=4, bias=False)
      (164): Linear(in_features=4, out_features=4, bias=False)
      (165): Linear(in_features=4, out_features=4, bias=False)
      (166): Linear(in_features=4, out_features=4, bias=False)
      (167): Linear(in_features=4, out_features=4, bias=False)
      (168): Linear(in_features=4, out_features=4, bias=False)
      (169): Linear(in_features=4, out_features=4, bias=False)
      (170): Linear(in_features=4, out_features=4, bias=False)
      (171): Linear(in_features=4, out_features=4, bias=False)
      (172): Linear(in_features=4, out_features=4, bias=False)
      (173): Linear(in_features=4, out_features=4, bias=False)
      (174): Linear(in_features=4, out_features=4, bias=False)
      (175): Linear(in_features=4, out_features=4, bias=False)
      (176): Linear(in_features=4, out_features=4, bias=False)
      (177): Linear(in_features=4, out_features=4, bias=False)
      (178): Linear(in_features=4, out_features=4, bias=False)
      (179): Linear(in_features=4, out_features=4, bias=False)
      (180): Linear(in_features=4, out_features=4, bias=False)
      (181): Linear(in_features=4, out_features=4, bias=False)
      (182): Linear(in_features=4, out_features=4, bias=False)
      (183): Linear(in_features=4, out_features=4, bias=False)
      (184): Linear(in_features=4, out_features=4, bias=False)
      (185): Linear(in_features=4, out_features=4, bias=False)
      (186): Linear(in_features=4, out_features=4, bias=False)
      (187): Linear(in_features=4, out_features=4, bias=False)
      (188): Linear(in_features=4, out_features=4, bias=False)
      (189): Linear(in_features=4, out_features=4, bias=False)
      (190): Linear(in_features=4, out_features=4, bias=False)
      (191): Linear(in_features=4, out_features=4, bias=False)
      (192): Linear(in_features=4, out_features=4, bias=False)
      (193): Linear(in_features=4, out_features=4, bias=False)
      (194): Linear(in_features=4, out_features=4, bias=False)
      (195): Linear(in_features=4, out_features=4, bias=False)
      (196): Linear(in_features=4, out_features=4, bias=False)
      (197): Linear(in_features=4, out_features=4, bias=False)
      (198): Linear(in_features=4, out_features=4, bias=False)
      (199): Linear(in_features=4, out_features=4, bias=False)
      (200): Linear(in_features=4, out_features=4, bias=False)
      (201): Linear(in_features=4, out_features=4, bias=False)
      (202): Linear(in_features=4, out_features=4, bias=False)
      (203): Linear(in_features=4, out_features=4, bias=False)
      (204): Linear(in_features=4, out_features=4, bias=False)
      (205): Linear(in_features=4, out_features=4, bias=False)
      (206): Linear(in_features=4, out_features=4, bias=False)
      (207): Linear(in_features=4, out_features=4, bias=False)
      (208): Linear(in_features=4, out_features=4, bias=False)
      (209): Linear(in_features=4, out_features=4, bias=False)
      (210): Linear(in_features=4, out_features=4, bias=False)
      (211): Linear(in_features=4, out_features=4, bias=False)
      (212): Linear(in_features=4, out_features=4, bias=False)
      (213): Linear(in_features=4, out_features=4, bias=False)
      (214): Linear(in_features=4, out_features=4, bias=False)
      (215): Linear(in_features=4, out_features=4, bias=False)
      (216): Linear(in_features=4, out_features=4, bias=False)
      (217): Linear(in_features=4, out_features=4, bias=False)
      (218): Linear(in_features=4, out_features=4, bias=False)
      (219): Linear(in_features=4, out_features=4, bias=False)
      (220): Linear(in_features=4, out_features=4, bias=False)
      (221): Linear(in_features=4, out_features=4, bias=False)
      (222): Linear(in_features=4, out_features=4, bias=False)
      (223): Linear(in_features=4, out_features=4, bias=False)
      (224): Linear(in_features=4, out_features=4, bias=False)
      (225): Linear(in_features=4, out_features=4, bias=False)
      (226): Linear(in_features=4, out_features=4, bias=False)
      (227): Linear(in_features=4, out_features=4, bias=False)
      (228): Linear(in_features=4, out_features=4, bias=False)
      (229): Linear(in_features=4, out_features=4, bias=False)
      (230): Linear(in_features=4, out_features=4, bias=False)
      (231): Linear(in_features=4, out_features=4, bias=False)
      (232): Linear(in_features=4, out_features=4, bias=False)
      (233): Linear(in_features=4, out_features=4, bias=False)
      (234): Linear(in_features=4, out_features=4, bias=False)
      (235): Linear(in_features=4, out_features=4, bias=False)
      (236): Linear(in_features=4, out_features=4, bias=False)
      (237): Linear(in_features=4, out_features=4, bias=False)
      (238): Linear(in_features=4, out_features=4, bias=False)
      (239): Linear(in_features=4, out_features=4, bias=False)
      (240): Linear(in_features=4, out_features=4, bias=False)
      (241): Linear(in_features=4, out_features=4, bias=False)
      (242): Linear(in_features=4, out_features=4, bias=False)
      (243): Linear(in_features=4, out_features=4, bias=False)
      (244): Linear(in_features=4, out_features=4, bias=False)
      (245): Linear(in_features=4, out_features=4, bias=False)
      (246): Linear(in_features=4, out_features=4, bias=False)
      (247): Linear(in_features=4, out_features=4, bias=False)
      (248): Linear(in_features=4, out_features=4, bias=False)
      (249): Linear(in_features=4, out_features=4, bias=False)
      (250): Linear(in_features=4, out_features=4, bias=False)
      (251): Linear(in_features=4, out_features=4, bias=False)
      (252): Linear(in_features=4, out_features=4, bias=False)
      (253): Linear(in_features=4, out_features=4, bias=False)
      (254): Linear(in_features=4, out_features=4, bias=False)
      (255): Linear(in_features=4, out_features=4, bias=False)
      (256): Linear(in_features=4, out_features=4, bias=False)
      (257): Linear(in_features=4, out_features=4, bias=False)
      (258): Linear(in_features=4, out_features=4, bias=False)
      (259): Linear(in_features=4, out_features=4, bias=False)
      (260): Linear(in_features=4, out_features=4, bias=False)
      (261): Linear(in_features=4, out_features=4, bias=False)
      (262): Linear(in_features=4, out_features=4, bias=False)
      (263): Linear(in_features=4, out_features=4, bias=False)
      (264): Linear(in_features=4, out_features=4, bias=False)
      (265): Linear(in_features=4, out_features=4, bias=False)
      (266): Linear(in_features=4, out_features=4, bias=False)
      (267): Linear(in_features=4, out_features=4, bias=False)
      (268): Linear(in_features=4, out_features=4, bias=False)
      (269): Linear(in_features=4, out_features=4, bias=False)
      (270): Linear(in_features=4, out_features=4, bias=False)
      (271): Linear(in_features=4, out_features=4, bias=False)
      (272): Linear(in_features=4, out_features=4, bias=False)
      (273): Linear(in_features=4, out_features=4, bias=False)
      (274): Linear(in_features=4, out_features=4, bias=False)
      (275): Linear(in_features=4, out_features=4, bias=False)
      (276): Linear(in_features=4, out_features=4, bias=False)
      (277): Linear(in_features=4, out_features=4, bias=False)
      (278): Linear(in_features=4, out_features=4, bias=False)
      (279): Linear(in_features=4, out_features=4, bias=False)
      (280): Linear(in_features=4, out_features=4, bias=False)
      (281): Linear(in_features=4, out_features=4, bias=False)
      (282): Linear(in_features=4, out_features=4, bias=False)
      (283): Linear(in_features=4, out_features=4, bias=False)
      (284): Linear(in_features=4, out_features=4, bias=False)
      (285): Linear(in_features=4, out_features=4, bias=False)
      (286): Linear(in_features=4, out_features=4, bias=False)
      (287): Linear(in_features=4, out_features=4, bias=False)
      (288): Linear(in_features=4, out_features=4, bias=False)
      (289): Linear(in_features=4, out_features=4, bias=False)
      (290): Linear(in_features=4, out_features=4, bias=False)
      (291): Linear(in_features=4, out_features=4, bias=False)
      (292): Linear(in_features=4, out_features=4, bias=False)
      (293): Linear(in_features=4, out_features=4, bias=False)
      (294): Linear(in_features=4, out_features=4, bias=False)
      (295): Linear(in_features=4, out_features=4, bias=False)
      (296): Linear(in_features=4, out_features=4, bias=False)
      (297): Linear(in_features=4, out_features=4, bias=False)
      (298): Linear(in_features=4, out_features=4, bias=False)
      (299): Linear(in_features=4, out_features=4, bias=False)
      (300): Linear(in_features=4, out_features=4, bias=False)
      (301): Linear(in_features=4, out_features=4, bias=False)
      (302): Linear(in_features=4, out_features=4, bias=False)
      (303): Linear(in_features=4, out_features=4, bias=False)
      (304): Linear(in_features=4, out_features=4, bias=False)
      (305): Linear(in_features=4, out_features=4, bias=False)
      (306): Linear(in_features=4, out_features=4, bias=False)
      (307): Linear(in_features=4, out_features=4, bias=False)
      (308): Linear(in_features=4, out_features=4, bias=False)
      (309): Linear(in_features=4, out_features=4, bias=False)
      (310): Linear(in_features=4, out_features=4, bias=False)
      (311): Linear(in_features=4, out_features=4, bias=False)
      (312): Linear(in_features=4, out_features=4, bias=False)
      (313): Linear(in_features=4, out_features=4, bias=False)
      (314): Linear(in_features=4, out_features=4, bias=False)
      (315): Linear(in_features=4, out_features=4, bias=False)
      (316): Linear(in_features=4, out_features=4, bias=False)
      (317): Linear(in_features=4, out_features=4, bias=False)
      (318): Linear(in_features=4, out_features=4, bias=False)
      (319): Linear(in_features=4, out_features=4, bias=False)
      (320): Linear(in_features=4, out_features=4, bias=False)
      (321): Linear(in_features=4, out_features=4, bias=False)
      (322): Linear(in_features=4, out_features=4, bias=False)
      (323): Linear(in_features=4, out_features=4, bias=False)
      (324): Linear(in_features=4, out_features=4, bias=False)
    )
  )
  (dnn): DNN(
    (dropout): Dropout(p=0, inplace=False)
    (linears): ModuleList(
      (0): Linear(in_features=2613, out_features=128, bias=True)
      (1): Linear(in_features=128, out_features=128, bias=True)
    )
    (activation_layers): ModuleList(
      (0): ReLU(inplace=True)
      (1): ReLU(inplace=True)
    )
  )
  (dnn_linear): Linear(in_features=128, out_features=1, bias=False)
)
'''